#include<bits/stdc++.h>
using namespace std;
int main()
{
    int num = 5;
    int *ptr = &num;
    cout << *ptr << " " << ptr << endl; 
    cout << &num << endl;

    float d = 4.65;
    float *ftr = &d;
    cout << ftr << " " << *ftr << endl;

    for (int integer = 0; integer < d; integer++)
    {
        cin >> first;
        for (float index = 0; index < count; index++)
        {
            /* code */
        }
        
    }
    return 0;
    
}